In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
# Data Manipulation
import numpy as np
import pandas as pd
pd.set_option("display.max_columns",None)

# Olist packages
from olist.data import Olist
from olist.review import Review
from olist.order import Order
from olist.product_updated import Product
from olist.seller_updated import Seller

In [7]:
data = Olist().get_data()

# Worst sellers

In [8]:
sellers = Seller().get_training_data()
sellers.columns

Index(['seller_id', 'seller_city', 'seller_state', 'delay_to_carrier',
       'wait_time', 'date_first_sale', 'date_last_sale', 'months_on_olist',
       'share_of_one_stars', 'share_of_five_stars', 'review_score',
       'cost_of_reviews', 'n_orders', 'quantity', 'quantity_per_order',
       'sales', 'revenues', 'profits'],
      dtype='object')

In [9]:
worst_sellers = sellers[["seller_id", "review_score", "profits"]].sort_values(
    by = "profits",
    ascending = True).head(10)
worst_sellers

                             seller_id  review_score    profits
769   6560211a19b47992c3666cc44a7e94c0      3.937093 -21439.517
2358  4a3ca9315b744ce9f8e9374361493884      3.827873 -17752.708
1357  cc419e0650a3c5ba77189a1882b7556a      4.077586 -17581.158
945   ea8482cd71df3c1969d7b9473ff13abc      3.997371 -15542.248
315   8b321bb669392f5163d04c59e235e066      4.074547 -12886.431
453   1f50f920176fa81dab994f9023523100      4.130342  -9926.079
1213  d2374cbcbb3ca4ab1086534108cc3ab7      3.751880  -8937.608
1132  7c67e1448b00f6e969d365cea6b010ab      3.488798  -7937.611
2023  cca3071e3e9bb7d12640c9fbe2301306      3.846369  -7379.011
2687  1835b56ce799e6a4dc4eddc053f04066      3.637441  -7135.579

# Worst products sold by them

In [10]:
products = Product().get_training_data() [["product_id", "category"]]
products

                             product_id                           category
0      1e9e8ef04dbcff4541ed26657ea517e5                          perfumery
1      6a2fb4dd53d2cdb88e0432f1284a004c                          perfumery
2      0d009643171aee696f4733340bc2fdd0                          perfumery
3      b1eae565a61935e0011ee7682fef9dc9                          perfumery
4      8da90b37f0fb171b4877c124f965b1f6                          perfumery
...                                 ...                                ...
31479  13b25797ad1e6d6c7cd3cbeb35f8ee7a  furniture_mattress_and_upholstery
31480  dc36a7859b743d8610a2bbbaea26ece9  furniture_mattress_and_upholstery
31481  107fde0930956120d1e13dd1062fbb46  furniture_mattress_and_upholstery
31482  726b4e18f00255e2e63491bcba3f60b8  furniture_mattress_and_upholstery
31483  1dceebcc5f23c02ea23e16d5bedca000                  cds_dvds_musicals

[31484 rows x 2 columns]

In [11]:
sellers_product_category = data["order_items"].merge(products,
                                             on = "product_id", how = "left")[["seller_id", "category"]]

sellers_product_category

                               seller_id               category
0       48436dade18ac8b2bce089ec2a041202             cool_stuff
1       dd7ddc04e1b6c2c614352b383efe2d36               pet_shop
2       5b51032eddd242adc84c38acab88f23d        furniture_decor
3       9d7a1d34a5052409006425275ba1c2b4              perfumery
4       df560393f3a51e74553ab94004ba5c87           garden_tools
...                                  ...                    ...
112645  b8bc237ba3788b23da09c0f1f3a3288c             housewares
112646  f3c38ab652836d21de61fb8314b69182  computers_accessories
112647  c3cfdc648177fdbbbb35635a37472c53         sports_leisure
112648  2b3e4a2a3ea8e01938cabda2a3e5cc79  computers_accessories
112649  f7ccf836d21b2fb1de37564105216cc1         bed_bath_table

[112650 rows x 2 columns]

In [12]:
sellers_various_products = sellers_product_category.groupby("seller_id").count()
sellers_various_products.columns = ["nb_of_different_categories_of_products"]
sellers_various_products.sort_values(
    by = "nb_of_different_categories_of_products",
    ascending = False).head(10)

                                  nb_of_different_categories_of_products
seller_id
6560211a19b47992c3666cc44a7e94c0                                    2029
4a3ca9315b744ce9f8e9374361493884                                    1979
1f50f920176fa81dab994f9023523100                                    1931
cc419e0650a3c5ba77189a1882b7556a                                    1775
da8622b14eb17ae2831f4ac5b9dab84a                                    1549
955fee9216a65b617aa5c0531780ce60                                    1498
1025f0e2d44d7041d6cf58b6550e0bfa                                    1423
7c67e1448b00f6e969d365cea6b010ab                                    1363
ea8482cd71df3c1969d7b9473ff13abc                                    1202
7a67c85e85bb2ce8582c35f2203ad736                                    1167

In [13]:
def focus_seller(seller_id):
    return sellers_product_category[sellers_product_category.seller_id == seller_id].value_counts()

In [15]:
for worst_seller in worst_sellers["seller_id"]:
    print("-"*50)
    print(f"Focusing on the seller #{worst_seller}...")
    print(focus_seller(worst_seller))

--------------------------------------------------
Focusing on the seller #6560211a19b47992c3666cc44a7e94c0...
seller_id                         category
6560211a19b47992c3666cc44a7e94c0  watches_gifts                1624
                                  fashion_bags_accessories      340
                                  audio                          32
                                  perfumery                      13
                                  computers_accessories          12
                                  sports_leisure                  7
                                  construction_tools_safety       1
dtype: int64
--------------------------------------------------
Focusing on the seller #4a3ca9315b744ce9f8e9374361493884...
seller_id                         category
4a3ca9315b744ce9f8e9374361493884  bed_bath_table     1566
                                  home_confort        243
                                  furniture_decor      84
                                  toys                 54
                                  home_comfort_2       26
                                  baby                  5
                                  cool_stuff            1
dtype: int64
--------------------------------------------------
Focusing on the seller #cc419e0650a3c5ba77189a1882b7556a...
seller_id                         category
cc419e0650a3c5ba77189a1882b7556a  health_beauty    1091
                                  perfumery         657
                                  telephony          25
                                  food                2
dtype: int64
--------------------------------------------------
Focusing on the seller #ea8482cd71df3c1969d7b9473ff13abc...
seller_id                         category
ea8482cd71df3c1969d7b9473ff13abc  telephony    1177
                                  auto           25
dtype: int64
--------------------------------------------------
Focusing on the seller #8b321bb669392f5163d04c59e235e066...
seller_id                         category
8b321bb669392f5163d04c59e235e066  electronics              909
                                  consoles_games            22
                                  musical_instruments       20
                                  computers_accessories     15
                                  stationery                14
                                  air_conditioning          11
                                  auto                       9
                                  garden_tools               6
                                  cool_stuff                 5
                                  telephony                  5
                                  sports_leisure             1
dtype: int64
--------------------------------------------------
Focusing on the seller #1f50f920176fa81dab994f9023523100...
seller_id                         category
1f50f920176fa81dab994f9023523100  garden_tools              1882
                                  baby                        42
                                  signaling_and_security       7
dtype: int64
--------------------------------------------------
Focusing on the seller #d2374cbcbb3ca4ab1086534108cc3ab7...
seller_id                         category
d2374cbcbb3ca4ab1086534108cc3ab7  bed_bath_table    597
                                  auto               22
                                  cool_stuff         11
                                  baby                1
dtype: int64
--------------------------------------------------
Focusing on the seller #7c67e1448b00f6e969d365cea6b010ab...
seller_id                         category
7c67e1448b00f6e969d365cea6b010ab  office_furniture         1232
                                  furniture_decor            91
                                  sports_leisure             18
                                  furniture_living_room      16
                                  auto                        3
                                  baby                        3
dtype: int64
--------------------------------------------------
Focusing on the seller #cca3071e3e9bb7d12640c9fbe2301306...
seller_id                         category
cca3071e3e9bb7d12640c9fbe2301306  furniture_decor           537
                                  bed_bath_table            241
                                  housewares                 19
                                  fashion_male_clothing      14
                                  fashio_female_clothing      6
                                  baby                        4
dtype: int64
--------------------------------------------------
Focusing on the seller #1835b56ce799e6a4dc4eddc053f04066...
seller_id                         category
1835b56ce799e6a4dc4eddc053f04066  bed_bath_table    550
                                  baby                5
dtype: int64